final_pro/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('groupapp/',include('groupapp.urls')),
    path('showapp/',include('showapp.urls')),
]

groupapp/urls.py
from django.urls import path
from groupapp import views

app_name = 'groupapp'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('registerlogic/', views.registerlogic, name='registerlogic'),
    path('collectface/',views.collect_face,name='collectface'),
    path('login/', views.login, name='login'),
    path('loginlogic/', views.loginlogic, name='loginlogic'),
    path('phonelogin/', views.phonelogin, name='phonelogin'),
    path('phonelogic/', views.phonelogic, name='phonelogic'),
    path('facelogin/',views.facelogin,name='facelogin'),
    path('checkname/',views.check_name,name='checkname'),
    path('sendcode/', views.send_code, name='sendcode'),
    path('add_face/', views.add_user_face, name='face'),
    path('check_code/',views.check_code, name='check_code'),
]

showapp/urls.py
from django.urls import path
from showapp import views

app_name = 'showapp'

urlpatterns = [
    path('menu/', views.menu, name='menu'),
    path('main/', views.main, name='main'),
    path('introduce/', views.introduce, name='introduce'),
    path('changePage/',views.changePage,name='changePage'),
    path('jumpPage/',views.jumpPage,name='jumpPage'),
    path('searchMsg/',views.searchMsg,name='searchMsg'),
    path('main/city_map/',views.city_map,name = 'city_map'),
]

groupapp/models.py
from django.db import models

# Create your models here.
class Person(models.Model):
    name = models.CharField(max_length=128)
    phone = models.CharField(max_length=11)
    email = models.CharField(max_length=128)
    password = models.CharField(max_length=20)
    status = models.BooleanField(default=False)
    class Meta:
        db_table = 't_person'

# class Facepic(models.Model):
#     face_path = models.CharField(max_length=255)
#     owner = models.ForeignKey(to=Person,on_delete=models.CASCADE)
#     class Meta:
#         db_table = 't_facepic'

groupapp/views.py
import base64
import hashlib
import os
import random
import re
import http.client
import string
import uuid
from urllib import parse
from django.shortcuts import render, HttpResponse, redirect
from .models import Person
from django.db import transaction
from groupapp.face_face import Face_to_Face as Fa


# Create your views here.
def register(request):
    return render(request, 'groupapp/register.html')


def registerlogic(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        email = request.POST.get('email')
        password = request.POST.get('password')
        if Person.objects.filter(name=name):  # 用户名需要唯一
            return redirect('groupapp:register')
        with transaction.atomic():
            user = Person(name=name, phone=phone, email=email, password=password)
            user.save()
            request.session['name'] = name  # 将注册后的name存入cookie,便于人脸识别时使用
            return redirect('groupapp:collectface')
    return redirect('groupapp:register')


def collect_face(request):
    if request.session.get('name'):
        return render(request, 'groupapp/collect_face.html')
    return redirect('groupapp:register')  # 如果session中不存在用户名信息，返回注册页面


def login(request):
    status = request.GET.get('status')  # 如果时从人脸识别部分进行登录，会传递状态参数
    if status == '1':
        name = request.session.get('name')
        user = Person.objects.get(name=name)
        user.status = 1
        user.save()
    return render(request, 'groupapp/login.html')


def loginlogic(request):
    if request.method == 'POST':
        code = request.POST.get('code')
        # print(request.session.get('code'))
        # print(request.COOKIES['code'])
        if code_to_code(request, code):
            return HttpResponse('none')
        name = request.POST.get('name')
        user = Person.objects.filter(name=name)
        if not user:  # 用户名查询不到，返回用户注册页面
            return HttpResponse('name_error')
        else:  # 用户名能够查询到

            if not user.status:  # 人脸识别状态未被激活，返回人脸采集页面
                request.session['name'] = name  # 将用户名保存进cookie
                return redirect('face')
            password = request.POST.get('password')  # 状态处于被激活状态，取密码进行验证
            if Person.objects.get(name=name, password=password):
                return HttpResponse('ok')
            return HttpResponse('pwd_error') # 密码错误，继续登录
    return HttpResponse('none')


def phonelogin(request):
    return render(request, 'groupapp/phonelogin.html')


def facelogin(request):
    return render(request, 'groupapp/facelogin.html')


def check_name(request):
    name = request.GET.get('name')
    if Person.objects.filter(name=name):
        user = Person.objects.get(name=name)
        if user.status:  # 有名可查，且状态已被激活，
            return HttpResponse('1')  # 允许人脸识别登录
        request.session['name'] = name  # 将name存入cookie,便于下一步人脸信息采集
        return HttpResponse('2')  # 返回到人脸收集页面
    return HttpResponse('3')  # 返回到注册页面。


def send_sms(mobile, account='C37538922', password='50bcebbf62f2455d9483f9002fbc1781'):
    # 用户名是登录用户中心->验证码短信->产品总览->APIID
    # 密码 查看密码请登录用户中心->验证码短信->产品总览->APIKEY
    code = mobile[7:]
    text = "您的验证码是：" + code + "。请不要把验证码泄露给其他人。"
    host = "106.ihuyi.com"
    sms_send_uri = "/webservice/sms.php?method=Submit"
    params = parse.urlencode(
        {'account': account, 'password': password, 'content': text, 'mobile': mobile, 'format': 'json'})
    headers = {"Content-type": "application/x-www-form-urlencoded", "Accept": "text/plain"}
    # conn = http.client.HTTPConnection(host, port=80, timeout=30)
    # conn.request("POST", sms_send_uri, params, headers)
    # response = conn.getresponse()
    # response_str = response.read()
    # conn.close()
    return code


def send_code(request):
    phone = request.GET.get('phone')
    if re.match(r"^1(3|4|5|7|8)\d{9}$", phone):
        code = send_sms(mobile=phone)  # 发送短信，获得短信码
        request.session[phone] = code  # 将短信存入session,key为phone,value为code
        return HttpResponse('ok')
    return HttpResponse('no')


def phonelogic(request):
    if request.method == 'POST':
        phone = request.POST.get('phone')
        code = request.POST.get('code')
        if request.session.get(phone) == code:
            return redirect('showapp:main')
    return redirect('groupapp:phonelogin')


def add_user_face(request):
    name = request.session.get('name')
    if not name:
        return HttpResponse('2')  # 用户名不存在，返回到注册页面
    mana = request.POST.get('mana')
    fa_im = request.POST.get('pp').replace("data:image/jpeg;base64,", "")
    num = request.POST.get('um')
    img = base64.b64decode(fa_im)
    try:
        with open(str(num) + '.jpg', 'bw') as b:
            b.write(img)
            b.close()
        if mana == 'add':
            face = Fa('user_face', 'user_face').add_face(name, str(num) + '.jpg')
        else:
            face = Fa('user_face', 'user_face').face_yanzheng(name, str(num) + '.jpg', 0.4)
        os.remove(str(num) + '.jpg')
        if face:
            return HttpResponse('1')
        else:
            return HttpResponse('0')
    except:
        return HttpResponse('0')


def check_code(request):
    try:
        session_dict = request.session['code']
    except:
        session_dict = {}
    cod = random.sample(string.ascii_lowercase + string.ascii_uppercase + string.digits, 16)
    random_code = "".join(cod)
    name = str(uuid.uuid4())
    res = HttpResponse(random_code)
    session_dict.update({name: random_code})
    request.session['code']=session_dict
    res.set_cookie('code',name,max_age=100)
    return res
#
def code_to_code(request,check_num):
    code_name = request.COOKIES['code']
    code = request.session.get('code')[code_name]
    h = hashlib.md5()
    h.update(code.encode())
    if h.hexdigest() == check_num:
        return True
    else:
        return False

templates/groupapp/introduce.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>百智招聘</title>
    <link href="/static/style/authority/basic_layout.css" rel="stylesheet" type="text/css">
    <link href="/static/style/authority/common_style.css" rel="stylesheet" type="text/css">
</head>
<body>
<div id="container">
    <table class="table" cellspacing="0" cellpadding="0" width="100%" align="center" border="0">
        <tr>
            <th colspan="2">系统版本</th>
        </tr>
        <tr>
            <td width="100" height="30">当前版本<span class="TableRow2"></span></td>
            <td style="text-align:left">百智招聘系统 4.1</td>
        </tr>
    </table>

</div>
<script src="{% static 'jquery.1.8.3.min.js' %}"></script>
<script src="{% static 'echarts.js' %}"></script>
<script src="{% static 'china.js' %}"></script>

<!-- 为ECharts准备一个具备大小（宽高）的Dom -->
<div id="map" style="width: 600px;height:400px;"></div>
<script type="text/javascript">
    // 基于准备好的dom，初始化echarts实例
    var chart = echarts.init(document.getElementById('map'));
    chart.setOption({
        tooltip: {},
        series: [{
            name: '用户分布图',
            type: 'map',
            map: 'china',
            data: []
            //data:[{name:'北京',value:100},{name:'河北',value:1000}]
        }]
    });
    // 异步加载数据
    $.get('{% url "showapp:city_map" %}').done(function (data) {
        // data的格式{data:[{name='省名',value:值}]}
        //填入数据
        chart.setOption({
            series: [{
                data: data['city_data']
            }]
        });
    });
</script>
</body>
</html>

templates/groupapp/login.html
<!doctype html>
{% load static %}
<html>
<head>
    <title>Home</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="keywords" content=""/>
    <script src="/static/scripts/jquery/jquery-1.4.4.min.js"></script>
    <script src="{% static 'md5.js' %}"></script>
    <script type="application/x-javascript"> addEventListener("load", function () {
        setTimeout(hideURLbar, 0);
    }, false);

    function hideURLbar() {
        window.scrollTo(0, 1);
    } </script>
    <!-- font files  -->
    <link href='https://fonts.googleapis.com/css?family=Muli:400,300' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Nunito:400,300,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="/static/style.css">
    <!-- /font files  -->
    <!-- css files -->
    <link href="{% static 'css/style.css' %}" rel='stylesheet' type='text/css' media="all"/>
    <script type="text/javascript" src="{% static 'check_huakuai.js' %}"></script>
    <script type="text/javascript" src="{% static 'lock.js' %}"></script>
    <!-- /css files -->
    <script>
        var name_flag = false;
        var password_flag = false;
        var code_flag = false;
        var photo_flag = false;
        var code = '';
        var hk = new Miwen(wen);
        hk.jiemi();

        function check_name(self) {
            var re = /^[^0-9][a-zA-Z0-9_]+$/;
            if (!self.value) {
                alert('Name can\'t be empty!')
            } else if (!re.test(self.value)) {
                alert('Name form error!')
            } else {
                name_flag = true;
            }
        }

        function check_password(self) {
            {#必须包含 大小写字母，@ 其中的两个#}
            var re1 = /@/;
            var re2 = /[a-z]/;
            var re3 = /[A-Z]/;
            var count = re1.test(self.value) + re2.test(self.value) + re3.test(self.value);
            if (!self.value) {
                alert('Password can\'t be empty!')
            } else if (count < 2) {
                alert('Password form error')
            } else {
                password_flag = true
            }
        }

        function check_submit() {
            $.ajaxSetup({
                data: {csrfmiddlewaretoken: '{{ csrf_token }}'}
            });
            var loginurl = '{% url "groupapp:loginlogic" %}';
            $.ajax({
                acycl: false,
                type: "POST",
                url: "{% url 'groupapp:check_code' %}",
                data: "csrfmiddlewaretoken=" + "{{ csrf_token }}",
                success: function (data) {
                    code = data;
                    SliderBar("slideBar", options,code)
                }
            });
        }

        function mysubmit(self) {
            if (name_flag && password_flag && code_flag) {
                $(self).parent().parent().submit();
            } else {
                alert('You can\'t submit now !')
            }
        }

        function phone() {
            location.href = '{% url 'groupapp:phonelogin' %}';
        }

        function face() {
            location.href = '{% url 'groupapp:facelogin' %}';
        }
    </script>


</head>
<body>
<h1>Login</h1>
<div class="log">
    <div class="content1">
        <h2>Login</h2>
        <form action="{% url 'groupapp:loginlogic' %}" method="post">
            {% csrf_token %}
            <input type="text" name="name" onchange="check_name(this)" placeholder='USERNAME'>
            <input type="password" name="password" onchange='check_password(this)' placeholder="PASSWORD">
            {#mysubmit(this)#}
            <div class="button-row">
                <input type="button" class="sign-in" value="Sign In" onclick="check_submit()">
                <input type="reset" class="reset" value="Reset">
                <div class="clear"></div>
            </div>
            {#            下面这个div是滑块验证码的#}
            <div id="check_img">
                <div id="slideBar" align="center"></div>
                <div class="button-row" align="center">
                    <input type="button" class="sign-in" value="Face lgoin" onclick="face()">
                    <input type="button" class="reset" value="Phone lgoin" onclick="phone()">
                </div>
            </div>
        </form>
    </div>
    {#    <div id="vidi">#}
    {#        <button class="register" onclick="openMedia()" id="openvideo">开启摄像头</button>#}
    {#        <button class="register" onclick="make_face()" id="takephoto" style="display: none">拍照</button>#}
    {#            <img id="imgTag" src="" alt="imgTag">#}
    {#            <button class="register" onclick="closeMedia()">关闭摄像头</button>#}
    {#        <video id="video" width="500px" height="500px" autoplay="autoplay"></video>#}
    {#        <canvas id="canvas" width="500px" height="500px" style="display: none"></canvas>#}
    {#    </div>#}
    {#    <div class="clear"></div>#}
    {#</div>#}
    <div class="footer">
        <p>Copyright &copy; <a href="http://www.baizhiedu.com/" target="_blank" title="百知教育">百知教育</a></p>
    </div>
    <script type="text/javascript">
        var dataList = ["0", "1"];
        {#这个不用动#}
        var options = {
            dataList: dataList,
            success: function () {
                {#成功时返回的数据#}
                code_flag = true;
            },
            fail: function () {
                {#失败时返回的 数据#}
                {#console.log("fail");#}
                code_flag = false;
                return check_submit();
            }
        };
    </script>

    <script>
        let mediaStreamTrack = null; // 视频对象(全局)
        window.num = 0;
        var dont = 0;
        var takephoto;

        function openMedia() {
            $('#video').css('display', 'block');
            $('#openvideo').css('display', 'none');
            $('#takephoto').css('display', 'block');
            let constraints = {
                video: {width: 500, height: 500},
                audio: true
            };
            //获得video摄像头
            let video = document.getElementById('video');
            let promise = navigator.mediaDevices.getUserMedia(constraints);
            promise.then((mediaStream) => {
                mediaStreamTrack = typeof mediaStream.stop === 'function' ? mediaStream : mediaStream.getTracks()[1];
                video.srcObject = mediaStream;
                video.play();
            });
        }

        function make_face() {
            takephoto = setInterval(takePhoto, 2000);

        }

        // 拍照
        function takePhoto() {
            //获得Canvas对象
            let video = document.getElementById('video');
            let canvas = document.getElementById('canvas');
            let ctx = canvas.getContext('2d');
            ctx.drawImage(video, 0, 0, 500, 500);
            // toDataURL  ---  可传入'image/png'---默认, 'image/jpeg'
            let img = document.getElementById('canvas').toDataURL().substring(22);
            $('#canvas').css('display', 'none');
            $.ajax({
                type: "POST",
                url: "{% url 'groupapp:face' %}",
                data: {pp: img, name: 'hehe', um: dont, csrfmiddlewaretoken: '{{ csrf_token }}'},
                success: function (msg) {
                    console.log(num);
                    if (msg === '1') {
                        closeMedia();
                        photo_flag = true;
                        alert('很好，我的数据库里有你的大饼脸');
                    }
                    dont += 1;
                    if (dont === 5) {
                        closeMedia();
                        alert('你不是我们的大饼脸');
                    }
                }
            });
        }

        // 关闭摄像头
        function closeMedia() {
            clearInterval(takephoto);
            mediaStreamTrack.stop();
            $('#video').css('display', 'none');
            $('#openvideo').css('display', 'block');
            $('#takephoto').css('display', 'none');
        }
    </script>


</body>
</html>

templates/groupapp/menu.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="text/javascript" src="/static/scripts/jquery/jquery-1.7.1.js"></script>
<link href="/static/style/authority/basic_layout.css" rel="stylesheet" type="text/css">
<link href="/static/style/authority/common_style.css" rel="stylesheet" type="text/css">
<script type="text/javascript" src="/static/scripts/authority/commonAll.js"></script>
<script type="text/javascript" src="/static/scripts/fancybox/jquery.fancybox-1.3.4.js"></script>
<script type="text/javascript" src="/static/scripts/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
    <script type="text/javascript" src="{% static 'security.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'style/authority/jquery.fancybox-1.3.4.css' %}" media="screen">
<script type="text/javascript" src="/static/scripts/artDialog/artDialog.js?skin=default"></script>
<title>百智招聘</title>

<style>
</style>
</head>
<body>
	<form id="submitForm" name="submitForm" action="" method="post">
		<input type="hidden" name="allIDCheck" value="" id="allIDCheck"/>
		<input type="hidden" name="fangyuanEntity.fyXqName" value="" id="fyXqName"/>
		<div id="container">
			<div class="ui_content">
				<div class="ui_text_indent">
					<div id="box_border">
						<div id="box_top">搜索</div>
						<div id="box_center">
							<select name="fangyuanEntity.fyXqCode" id="fyXq" class="ui_select01">
                                <option value="other">--请选择--</option>
                                <option value="city">城市</option>
                                <option value="position">职位</option>
                            </select>
							<input type="text" id="fyZldz" name="fangyuanEntity.fyZldz" class="ui_input_txt02" />
							<input type="button" value="查询" class="ui_input_btn01" onclick="searchMsg()" />
						</div>
					</div>
				</div>
			</div>
			<div class="ui_content">
				<div class="ui_tb">
					<table class="table" cellspacing="0" cellpadding="0" width="100%" align="center" border="0">
						<tr>
							
						
							<th>姓名</th>
							<th>性别</th>
							<th>年龄</th>
							<th>籍贯</th>
							<th>现居住地</th>
							<th>期望职位</th>
							<th>期望城市</th>
							<th>期望薪资</th>
						</tr>
                        {% for i in page.object_list %}
                            <tr>
								<td>{{ i.name }}</td>
								<td>{{ i.gender }}</td>
								<td>{{ i.age }}</td>
								<td>{{ i.hometown }}</td>
								<td>{{ i.living_place }}</td>
								<td>{{ i.ideal_position }}</td>
								<td>{{ i.ideal_city }}</td>
								<td>{{ i.salary }}</td>
							</tr>
                        {% endfor %}


		
					</table>
				</div>
				<div class="ui_tb_h30">
					<div class="ui_flt" style="height: 30px; line-height: 30px;">
						共有
						<span class="ui_txt_bold04">{{ page.paginator.count }}</span>
						条记录，当前第
						<span class="ui_txt_bold04"><span id="p_msg">{{ number }}</span>/{{ page.paginator.num_pages }}</span>
						页
					</div>
					<div class="ui_frt">
						<!--    如果是第一页，则只显示下一页、尾页 -->
						
							<input type="button" value="首页" class="ui_input_btn01" onclick="firstPage('f')" />
                            <input id="previous" style="visibility: hidden" type="button" value="上一页" class="ui_input_btn01" onclick="firstPage('f12543541254')" />
                            <input id="next" style="visibility: visible" type="button" value="下一页" class="ui_input_btn01 " onclick="firstPage('f12543451254')" />
							<input type="button" value="尾页" class="ui_input_btn01" onclick="firstPage('l')" />
							<!--     如果是最后一页，则只显示首页、上一页 -->
						
						转到第<input id="jump" type="text" id="jumpNumTxt" class="ui_input_txt01" oninput = "value=value.replace(/[^\d]/g,'')" />页
							 <input type="button" class="ui_input_btn01" value="跳转" onclick="jumpPage()" />
                                <input type="hidden" value="{{ solt }}" name="pubkeyn" id="pubkeyn">

                    </div>
				</div>
			</div>
		</div>
	</form>
    <script type="text/javascript" src="{% static 'jquery.1.8.3.min.js' %}"></script>
    <script>
        function firstPage(p) {
            console.log(p,'gggggg');
            p = p+'';
            var xhr;
            if(window.ActiveXObject){
                xhr = new ActiveXObject('Microsoft.XMLHTTP')
            }else if(window.XMLHttpRequest){
                xhr = new XMLHttpRequest()
            }
            if (p === 'f12543541254') {
                var pn = Number(document.getElementById("p_msg").innerText)-1;
            }else if(p === 'f12543451254'){
                var pn = Number(document.getElementById("p_msg").innerText)+1;
            }
            else{
                var pn = p
            }
            console.log(pn,'44444444444444444444444444')
            xhr.open('get','{% url 'showapp:changePage' %}?city={{ city }}&job_type={{ job_type }}&v='+p+'&pn='+pn,true);

            xhr.send()
            xhr.onreadystatechange=function () {
                if (xhr.readyState === 4 && xhr.status === 200){
                    var text = xhr.responseText;
                    var number = eval("("+text+")")['number'];
                    console.log('yeshuuuuuuuuuuuuuuuu',number);
                    document.getElementById("p_msg").innerHTML=number;


                    var nextstate = eval("("+text+")")['nextstate'];
                    if(nextstate === 'nextok'){
                        document.getElementById("next").style.visibility ="visible";

                    }else if (nextstate === 'nextno'){
                        document.getElementById("next").style.visibility ="hidden";
                    }
                    else{
                        console.log('126')
                    }

                    var previousstate = eval("("+text+")")['previousstate'];
                    console.log(previousstate,'mmppppppppppppp')
                    if(previousstate === "previousok"){
                        document.getElementById("previous").style.visibility ="visible";

                    }else if(previousstate === "previousno"){
                        document.getElementById("previous").style.visibility ="hidden";
                    }else{
                        console.log('136')
                    }


                    msg = eval("("+text+")")['msgs'];
                    var s = "<tr>\n" +
                        "\t\t\t\t\t\t\t\n" +
                        "\t\t\t\t\t\t\n" +
                        "\t\t\t\t\t\t\t<th>姓名</th>\n" +
                        "\t\t\t\t\t\t\t<th>性别</th>\n" +
                        "\t\t\t\t\t\t\t<th>年龄</th>\n" +
                        "\t\t\t\t\t\t\t<th>籍贯</th>\n" +
                        "\t\t\t\t\t\t\t<th>现居住地</th>\n" +
                        "\t\t\t\t\t\t\t<th>期望职位</th>\n" +
                        "\t\t\t\t\t\t\t<th>期望城市</th>\n" +
                        "\t\t\t\t\t\t\t<th>期望薪资</th>\n" +
                        "\t\t\t\t\t\t</tr>";
                    for(var i=0;i<msg.length;i++){
                        s = s + "<tr><td>"+msg[i]["name"]+"</td> <td>"+msg[i]["gender"]+"</td><td>"+msg[i]["age"]+"</td> <td>"+msg[i]["hometown"]+"</td><td>"+msg[i]["living_place"]+"</td> <td>"+msg[i]["ideal_position"]+"</td> <td>"+msg[i]["ideal_city"]+"</td> <td>"+msg[i]["salary"]+"</td></tr>"
                        console.log(msg[i])
                    }
                    console.log(s);
                    $('tr').remove();
                    $("table").prepend(s);
                }
            }
        }
        function pass(p) {

        }
        var key ;
        function bodyRSA(){
	//setMaxDigits(130);

  	key = RSAUtils.getKeyPair("010001","","0098471b9a05c816ee949b4fe93520a8681a14e65d7a0501221136951a52a3b76cf9e2375e45aca1ad6fc9f00b401ece966a1f8fb521dd9de4215c90b7e9cd77b1c7d2f6e9b7aba6f94322d7375cbb321be653826d921030b6ef9fd453a7ece0ae4785a6166dd5d1560f3992cbad493201bb18616251610890bd0ea6736c346e15");

}


        function jumpPage() {
           var number = document.getElementById("jump").value
           console.log(number,'pageeeeeeeeeeeeeeeeeeeeeeeeeeeeee');
           var xhr;
           if(window.ActiveXObject){
               xhr=new ActiveXObject('Microsoft.XMLHTTP')
           }else if(window.XMLHttpRequest){
               xhr = new XMLHttpRequest()
           }
           var solt = document.getElementById('pubkeyn').value;

           number = (number*Number(solt)-Number(solt));
           console.log(number,'numbertttttttttttttt');
           xhr.open('get','{% url 'showapp:jumpPage' %}?city={{ city }}&job_type={{ job_type }}&number='+number,true);
           xhr.send();
           xhr.onreadystatechange=function () {
               if(xhr.readyState === 4 && xhr.status===200){
                   var text = xhr.responseText;
                   var number = eval("("+text+")")['number'];

                   delete window.solt;
                   var new_solt =  eval("("+text+")")['new_solt'];

                   document.getElementById('pubkeyn').value = new_solt;

                   document.getElementById("p_msg").innerHTML=number;

                   var nextstate = eval("("+text+")")['nextstate'];

                   if(nextstate === 'nextok'){
                       document.getElementById("next").style.visibility ="visible";

                   }else if (nextstate === 'nextno'){
                       document.getElementById("next").style.visibility ="hidden";
                   }
                   else{
                       console.log('185')
                   }


                   var previousstate = eval("("+text+")")['previousstate'];
                   console.log(previousstate,'previousstateeeeeeee')
                   if(previousstate === "previousok"){
                       document.getElementById("previous").style.visibility ="visible";

                   }else if(previousstate === "previousno"){
                       document.getElementById("previous").style.visibility ="hidden";
                   }else{
                       console.log('200')
                   }

                   msg = eval("("+text+")")['msgs'];
                   var s = "<tr>\n" +
                       "\t\t\t\t\t\t\t\n" +
                       "\t\t\t\t\t\t\n" +
                       "\t\t\t\t\t\t\t<th>姓名</th>\n" +
                       "\t\t\t\t\t\t\t<th>性别</th>\n" +
                       "\t\t\t\t\t\t\t<th>年龄</th>\n" +
                       "\t\t\t\t\t\t\t<th>籍贯</th>\n" +
                       "\t\t\t\t\t\t\t<th>现居住地</th>\n" +
                       "\t\t\t\t\t\t\t<th>期望职位</th>\n" +
                       "\t\t\t\t\t\t\t<th>期望城市</th>\n" +
                       "\t\t\t\t\t\t\t<th>期望薪资</th>\n" +
                       "\t\t\t\t\t\t</tr>";
                   for(var i=0;i<msg.length;i++){
                       s = s + "<tr><td>"+msg[i]["name"]+"</td> <td>"+msg[i]["gender"]+"</td><td>"+msg[i]["age"]+"</td> <td>"+msg[i]["hometown"]+"</td><td>"+msg[i]["living_place"]+"</td> <td>"+msg[i]["ideal_position"]+"</td> <td>"+msg[i]["ideal_city"]+"</td> <td>"+msg[i]["salary"]+"</td></tr>"
                   }
                       console.log(s);
                       $('tr').remove();
                       $("table").prepend(s);
               }
           }
        }
        function searchMsg() {
            var myselect = document.getElementById('fyXq');
            var msg = document.getElementById('fyZldz').value;
            var index = myselect.selectedIndex;
            console.log(index,msg,'choiceeeeeeeeeeeeee')
            var xhr;
            if (window.ActiveXObject){
                xhr = new ActiveXObject('Microsoft.XMLHTTP')
            }else if(window.XMLHttpRequest){
                xhr = new XMLHttpRequest()
            }
            xhr.open('post','{% url 'showapp:searchMsg' %}',true)
            xhr.setRequestHeader('Content-type','application/x-www-form-urlencoded')
            xhr.setRequestHeader('X-CSRFToken','{{ csrf_token }}')
            xhr.send('index='+index+'&msg='+msg)
            xhr.onreadystatechange=function () {
                if (xhr.readyState===4 && xhr.status===200){
                    var text = xhr.responseText;
                    console.log(text,'texttttttttttttttttttt')
                }
            }

        }


    </script>

</body>
</html>